// <auto-generated />
using System;
using AuctionProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuctionProject.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181206105742_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("AuctionProject.Models.AutoBid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("LotId");

                    b.Property<int>("MaxPrice");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("LotId");

                    b.HasIndex("UserID");

                    b.ToTable("AutoBids");
                });

            modelBuilder.Entity("AuctionProject.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LotId");

                    b.Property<int>("Price");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("AuctionProject.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("StartPrice");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("AuctionProject.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AuctionProject.Models.AutoBid", b =>
                {
                    b.HasOne("AuctionProject.Models.Lot", "Lot")
                        .WithMany("AutoBids")
                        .HasForeignKey("LotId");

                    b.HasOne("AuctionProject.Models.User", "User")
                        .WithMany("AutoBids")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("AuctionProject.Models.Bid", b =>
                {
                    b.HasOne("AuctionProject.Models.Lot", "Lot")
                        .WithMany("Bids")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AuctionProject.Models.User", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuctionProject.Models.Lot", b =>
                {
                    b.HasOne("AuctionProject.Models.User", "User")
                        .WithMany("Lots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
